- alias: Automatic Bar Lighting
  trigger:
  - platform: state
    entity_id: light.tradfri_bulb_e27_ws_opal_980lm
    to: 'on'
  - platform: time
    minutes: '/1'
    seconds: 00
  action:
  - service: switch.bar_automatic_lighting_update

- alias: Automatic Bar Lighting Notification
  trigger:
  - platform: state
    entity_id: automation.automatic_bar_lighting
    to: 'off'
  action:
  - service: notify.rocketchat_status
    data:
      message: ":bulb: Someone disabled the automatic bar lighting"
  - service: persistent_notification.create
    data:
      title: "Please tell Benj"
      message: "Benj would really like to know why you would like to disable the automatic lighting so he can optimize it and everyone is happy :)  Or contribute a fix yourself, code is on GitHub (puzzle/home-assistant-config)"
      notification_id: 222
  - delay:
      minutes: 1
  - service: persistent_notification.dismiss
    data:
      notification_id: 222

- alias: Low Battery Alert
  trigger:
    platform: numeric_state
    entity_id:
    - sensor.tradfri_motion_sensor
    below: 20
  action:
  - service: notify.rocketchat_status
    data_template:
      message: ":battery: {{ trigger.to_state.name }} is less than 20% battery"

- alias: Update Notification
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
  - service: notify.rocketchat_status
    data:
      message: "Home Assistant {{ trigger.to_state.state }} is available."

- alias: Startup Notification
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: notify.rocketchat_status
    data:
      message: ":hass: Home Assistant is up and running"

- alias: Shutdown Notification
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - service: notify.rocketchat_status
    data:
      message: ":hass: Home Assistant is stopped"

