- alias: Automatic Bar Lighting
  trigger:
  - platform: state
    entity_id: light.tradfri_bulb_e27_ws_opal_980lm
    from: 'off'
    to: 'on'
  - platform: time
    minutes: '/1'
    seconds: 00
  action:
  - service: switch.bar_automatic_lighting_update

- alias: Low battery alert
  trigger:
    platform: numeric_state
    entity_id:
    - sensor.tradfri_motion_sensor
    below: 20
  action:
  - service: notify.rocketchat_status
    data_template:
      message: ':battery: {{ trigger.to_state.name }} is less than 20% battery'

- alias: Update notification
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
  - service: notify.rocketchat_status
    data:
      message: ':hass: There is a new Home Assistant release available - <{{ states.updater.updater.attributes.release_notes }}>'

- alias: Startup notification
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: notify.rocketchat_status
    data:
      message: ':hass: Home Assistant is up and running'

- alias: Shutdown notification
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - service: notify.rocketchat_status
    data:
      message: ':hass: Home Assistant is stopped'

