- alias: "Bar Daylight"
  trigger:
  - platform: state
    entity_id: group.bar_lights
  condition:
  - condition: time
    after: '06:00:00'
    before: '16:00:00'
  action:
  - service: scene.turn_on
    entity_id: scene.bar_focus
- alias: "Bar Nightlight"
  trigger:
  - platform: state
    entity_id: group.bar_lights
  condition:
  - condition: time
    after: '06:00:00'
    before: '16:00:00'
  action:
  - service: switch.turn_on
    entity_id: switch.bar_nightlight

