- platform: generic
  name: Wankdorf A1 Richtung Zürich
  still_image_url: http://www.tbamobcam.ch/tbastrecke/tba010/stb_cam20.jpg
  scan_interval: 600
- platform: generic
  name: Wankdorf A6 Richtung Thun
  still_image_url: http://www.tbamobcam.ch/tbastrecke/tba008/stb_cam38.jpg
  scan_interval: 600
- platform: generic
  name: Wankdorf A6 Richtung Lausanne
  still_image_url: http://www.tbamobcam.ch/tbastrecke/tba009/stb_cam39.jpg
  scan_interval: 600

