- platform: travisci
  api_key: !secret travis_api_key
  repository:
  - puzzle/home-assistant-config
  entity_namespace: travis
- platform: rest
  name: Aare
  resource: http://aare.schwumm.ch/aare.json
  unit_of_measurement: "°C"
  value_template: '{{ value_json.temperature }}'
  scan_interval: 3600
- platform: mqtt
  name: sonoff-1688
  state_topic: "be3/tux/projector/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"

